MESSAGE_TEMPLATES = {
    "AU0": {"audit_class": "Other Events", "message_severity": "Low", "message_text": "Audit - Test. Text: &A"},
    "AU1": {"audit_class": "Dialog Logon", "message_severity": "Medium", "message_text": "Logon successful (type=&A, method=&C)"},
    "AU2": {"audit_class": "Dialog Logon", "message_severity": "High", "message_text": "Logon failed (reason=&B, type=&A, method=&C)"},
    "AU3": {"audit_class": "Transaction Start", "message_severity": "Low", "message_text": "Transaction &A started."},
    "AU4": {"audit_class": "Transaction Start", "message_severity": "High", "message_text": "Start of transaction &A failed (Reason=&B)"},
    "AU5": {"audit_class": "RFC/CPIC Logon", "message_severity": "Low", "message_text": "RFC/CPIC logon successful (type=&A, method=&C)"},
    "AU6": {"audit_class": "RFC/CPIC Logon", "message_severity": "High", "message_text": "RFC/CPIC logon failed, reason=&B, type=&A, method=&C"},
    "AU7": {"audit_class": "User Master Changes", "message_severity": "High", "message_text": "User &A created."},
    "AU8": {"audit_class": "User Master Changes", "message_severity": "High", "message_text": "User &A deleted."},
    "AU9": {"audit_class": "User Master Changes", "message_severity": "Medium", "message_text": "User &A locked."},
    "AUA": {"audit_class": "User Master Changes", "message_severity": "Medium", "message_text": "User &A unlocked."},
    "AUB": {"audit_class": "User Master Changes", "message_severity": "Medium", "message_text": "Authorizations for user &A changed."},
    "AUC": {"audit_class": "Dialog Logon", "message_severity": "Low", "message_text": "User Logoff"},
    "AUD": {"audit_class": "User Master Changes", "message_severity": "Medium", "message_text": "User master record &A changed."},
    "AUE": {"audit_class": "System Events", "message_severity": "High", "message_text": "Audit configuration changed"},
    "AUF": {"audit_class": "System Events", "message_severity": "High", "message_text": "Audit: Slot &A: Class &B, Severity &C, User &D, Client &E, &F"},
    "AUG": {"audit_class": "System Events", "message_severity": "High", "message_text": "Application server started"},
    "AUH": {"audit_class": "System Events", "message_severity": "High", "message_text": "Application server stopped"},
    "AUI": {"audit_class": "System Events", "message_severity": "High", "message_text": "Audit: Slot &A Inactive"},
    "AUJ": {"audit_class": "System Events", "message_severity": "High", "message_text": "Audit: Active status set to &1"},
    "AUK": {"audit_class": "RFC Function Call", "message_severity": "Low", "message_text": "Successful RFC call &C (function group = &A)"},
    "AUL": {"audit_class": "RFC Function Call", "message_severity": "High", "message_text": "Failed RFC call &C (function group = &A)"},
    "AUM": {"audit_class": "Dialog Logon", "message_severity": "High", "message_text": "User &B locked in client &A after errors in password checks"},
    "AUN": {"audit_class": "Dialog Logon", "message_severity": "High", "message_text": "User &B unlocked in client &A after entering wrong password"},
    "AUO": {"audit_class": "Dialog Logon", "message_severity": "Medium", "message_text": "Logon failed (reason = &B, type = &A)"},
    "AUP": {"audit_class": "Transaction Start", "message_severity": "Medium", "message_text": "Transaction &A locked"},
    "AUQ": {"audit_class": "Transaction Start", "message_severity": "Medium", "message_text": "Transaction &A unlocked"},
    "AUR": {"audit_class": "User Master Changes", "message_severity": "Medium", "message_text": "&A &B created"},
    "AUS": {"audit_class": "User Master Changes", "message_severity": "Medium", "message_text": "&A &B deleted"},
    "AUT": {"audit_class": "User Master Changes", "message_severity": "Medium", "message_text": "&A &B changed"},
    "AUU": {"audit_class": "User Master Changes", "message_severity": "High", "message_text": "&A &B activated"},
    "AUV": {"audit_class": "Other Events", "message_severity": "High", "message_text": "Digital signature error (reason = &A, ID = &B)"},
    "AUW": {"audit_class": "Report Start", "message_severity": "Low", "message_text": "Report &A started"},
    "AUX": {"audit_class": "Report Start", "message_severity": "Medium", "message_text": "Start of report &A failed (reason = &B)"},
    "AUY": {"audit_class": "Other Events", "message_severity": "Medium", "message_text": "Download &A Bytes to File &C"},
    "AUZ": {"audit_class": "Other Events", "message_severity": "Medium", "message_text": "Digital Signature (Reason = &A, ID = &B)"},
    "BU0": {"audit_class": "Other Events", "message_severity": "High", "message_text": "RAL configuration access: Action: &A, type: &B, name &C"},
    "BU1": {"audit_class": "Other Events", "message_severity": "High", "message_text": "Password check failed for user &B in client &A"},
    "BU2": {"audit_class": "User Master Changes", "message_severity": "Low", "message_text": "Password changed for user &B in client &A"},
    "BU3": {"audit_class": "Other Events", "message_severity": "High", "message_text": "Security check changed in export: Old value &A, new value &B"},
    "BU4": {"audit_class": "Other Events", "message_severity": "Low", "message_text": "Dynamic ABAP code: Event &A, event type &B, check total &C"},
    "BU5": {"audit_class": "Other Events", "message_severity": "Medium", "message_text": "ICF recorder entry executed for user &A (activity &B)"},
    "BU6": {"audit_class": "Other Events", "message_severity": "Medium", "message_text": "ICF recorder entry executed by user &A (&B, &C) (activity &D)."},
    "BU7": {"audit_class": "Other Events", "message_severity": "Medium", "message_text": "Administration setting was changed for ICF Recorder (Activity: &A)"},
    "BU8": {"audit_class": "Other Events", "message_severity": "High", "message_text": "Virus Scan Interface: Virus \"&C\" found by profile &A (step &B)"},
    "BU9": {"audit_class": "Other Events", "message_severity": "Medium", "message_text": "Virus Scan Interface: Error \"&C\" occurred in profile &A (step &B)"},
    "BUA": {"audit_class": "Other Events", "message_severity": "Medium", "message_text": "WS: Signature check error (reason &B, WP &C). Refer to Web service log &A."},
    "BUB": {"audit_class": "Other Events", "message_severity": "Medium", "message_text": "WS: Signature insufficient (WP &C). Refer to Web service log &A."},
    "BUC": {"audit_class": "Other Events", "message_severity": "Medium", "message_text": "WS: Time stamp is invalid. Refer to Web service log &A."},
    "BUD": {"audit_class": "Dialog Logon", "message_severity": "High", "message_text": "WS: Delayed logon failed (type &B, WP &C). Refer to Web service log &A."},
    "BUE": {"audit_class": "Dialog Logon", "message_severity": "High", "message_text": "WS: Delayed logon successful (type &B, WP &C). Refer to Web service log &A."},
    "BUF": {"audit_class": "Other Events", "message_severity": "Low", "message_text": "HTTP Security Session Management was activated for client &A."},
    "BUG": {"audit_class": "Other Events", "message_severity": "High", "message_text": "HTTP Security Session Management was deactivated for client &A."},
    "BUH": {"audit_class": "Other Events", "message_severity": "Medium", "message_text": "HTTP Security Session of user &A (client &B) was hard exited"},
    "BUI": {"audit_class": "Dialog Logon", "message_severity": "High", "message_text": "SPNego replay attack detected (UPN=&A)"},
    "BUJ": {"audit_class": "Other Events", "message_severity": "Medium", "message_text": "Non-encrypted &A communication (&B)"},
    "BUK": {"audit_class": "Dialog Logon", "message_severity": "Low", "message_text": "&A assertion used"},
    "BUL": {"audit_class": "Dialog Logon", "message_severity": "Low", "message_text": "&A: &B"},
    "BUM": {"audit_class": "Dialog Logon", "message_severity": "Low", "message_text": "Name ID of a subject"},
    "BUN": {"audit_class": "Dialog Logon", "message_severity": "Low", "message_text": "Attribute"},
    "BUO": {"audit_class": "Dialog Logon", "message_severity": "Low", "message_text": "Authentication assertion"},
    "BUP": {"audit_class": "Dialog Logon", "message_severity": "Low", "message_text": "&A"},
    "BUQ": {"audit_class": "Dialog Logon", "message_severity": "Low", "message_text": "Signed LogoutRequest accepted"},
    "BUR": {"audit_class": "Dialog Logon", "message_severity": "Low", "message_text": "Unsigned LogoutRequest accepted"},
    "BUS": {"audit_class": "Other Events", "message_severity": "High", "message_text": "&A: Request without sufficient security characteristic of address &B."},
    "BUT": {"audit_class": "Other Events", "message_severity": "Medium", "message_text": "CRL download failed with error code &A"},
    "BUU": {"audit_class": "Other Events", "message_severity": "High", "message_text": "Certificate check for subject \"&A\" with profile &B failed (status &C)"},
    "BUV": {"audit_class": "User Master Changes", "message_severity": "High", "message_text": "Invalid hash value &A. The context contains &B."},
    "BUW": {"audit_class": "User Master Changes", "message_severity": "High", "message_text": "A refresh token issued to client &A was used by client &B."},
    "BUX": {"audit_class": "RFC Function Call", "message_severity": "High", "message_text": "CCMS method &A was started on destination &B"},
    "BUY": {"audit_class": "Other Events", "message_severity": "High", "message_text": "Field contents changed: &5&9&9&9&9&9"},
    "BUZ": {"audit_class": "Other Events", "message_severity": "High", "message_text": "> in program &A, line &B, event &C"},
    "CU0": {"audit_class": "Other Events", "message_severity": "High", "message_text": "RAL Log Access: Action: &A"},
    "CU1": {"audit_class": "Other Events", "message_severity": "Medium", "message_text": "CU Test Message"},
    "CU2": {"audit_class": "Dialog Logon", "message_severity": "Medium",
            "message_text": "OAuth 2.0: Invalid access token received (reason=&A)"},
    "CU3": {"audit_class": "Dialog Logon", "message_severity": "Medium",
            "message_text": "OAuth 2.0: Insufficient OAuth 2.0 scope for requested resource (user=&A)"},
    "CU4": {"audit_class": "Dialog Logon", "message_severity": "High",
            "message_text": "OAuth 2.0: Logged-on client user &A not same as parameter client ID &B"},
    "CU5": {"audit_class": "Dialog Logon", "message_severity": "Medium",
            "message_text": "OAuth 2.0: Client &A requested invalid access grant type &B"},
    "CU6": {"audit_class": "Dialog Logon", "message_severity": "High",
            "message_text": "OAuth 2.0: Client ID &A in SAML assertion not same as client ID &B in request"},
    "CU7": {"audit_class": "Dialog Logon", "message_severity": "Medium",
            "message_text": "OAuth 2.0: Scope &B not permitted for client &C, user &D (cause=&A)"},
    "CU8": {"audit_class": "Dialog Logon", "message_severity": "Low",
            "message_text": "OAuth 2.0: Access token issued (client=&A, user=&B, grant type=&C)"},
    "CU9": {"audit_class": "Dialog Logon", "message_severity": "Low",
            "message_text": "OAuth 2.0: Valid access token received for user &A"},
    "CUA": {"audit_class": "Dialog Logon", "message_severity": "Medium", "message_text": "Rejected Assertion"},
    "CUB": {"audit_class": "Dialog Logon", "message_severity": "Medium", "message_text": "&A: &B"},
    "CUC": {"audit_class": "Dialog Logon", "message_severity": "Medium", "message_text": "&A"},
    "CUD": {"audit_class": "Dialog Logon", "message_severity": "Medium", "message_text": "Name ID of a subject"},
    "CUE": {"audit_class": "Dialog Logon", "message_severity": "Medium", "message_text": "Attribute"},
    "CUF": {"audit_class": "Dialog Logon", "message_severity": "Medium", "message_text": "Authentication Assertion"},
    "CUG": {"audit_class": "Dialog Logon", "message_severity": "Medium",
            "message_text": "Signed LogoutRequest rejected"},
    "CUH": {"audit_class": "Dialog Logon", "message_severity": "Medium",
            "message_text": "Unsigned LogoutRequest rejected"},
    "CUI": {"audit_class": "Transaction Start", "message_severity": "Low", "message_text": "Application &A started"},
    "CUJ": {"audit_class": "Transaction Start", "message_severity": "High",
            "message_text": "Failed to start application &A (reason =&B)"},
    "CUK": {"audit_class": "Other Events", "message_severity": "High", "message_text": "C debugging activated"},
    "CUL": {"audit_class": "Other Events", "message_severity": "High",
            "message_text": "Field content in debugger changed by user &A(&B): &C (&D)"},
    "CUM": {"audit_class": "Other Events", "message_severity": "High",
            "message_text": "Jump to ABAP Debugger by user &A(&B): &C (&D)"},
    "CUN": {"audit_class": "Other Events", "message_severity": "High",
            "message_text": "A process was stopped from the debugger by user &A(&B) (&D)"},
    "CUO": {"audit_class": "Other Events", "message_severity": "High",
            "message_text": "Explicit database operation in debugger by user &A(&B): &C (&D)"},
    "CUP": {"audit_class": "Other Events", "message_severity": "High",
            "message_text": "Non-exclusive debugging session started by user &A(&B) (&D)"},
    "CUQ": {"audit_class": "Other Events", "message_severity": "Medium",
            "message_text": "Logical file name &A not configured. Physical file name &B not checked."},
    "CUR": {"audit_class": "Other Events", "message_severity": "Medium",
            "message_text": "Physical file name &B does not fulfill requirements from logical file name &A"},
    "CUS": {"audit_class": "Other Events", "message_severity": "Medium",
            "message_text": "Logical file name &B is not a valid alias for logical file name &A"},
    "CUT": {"audit_class": "Other Events", "message_severity": "Medium",
            "message_text": "Validation for logical file name &A is not active"},
    "CUU": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "Payload of PI/WS message &A was read | &B"},
    "CUV": {"audit_class": "RFC Function Call", "message_severity": "Low",
            "message_text": "Successful WS Call (service = &A, operation &B)"},
    "CUW": {"audit_class": "RFC Function Call", "message_severity": "High",
            "message_text": "Failed Web service call (service = &A, operation = &B, reason = &C)"},
    "CUX": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "Payload of postprocessing request &A read"},
    "CUY": {"audit_class": "Other Events", "message_severity": "Low", "message_text": "> &A"},
    "CUZ": {"audit_class": "RFC Function Call", "message_severity": "High",
            "message_text": "Generic table access by RFC to &A with activity &B"},
    "DU0": {"audit_class": "Dialog Logon", "message_severity": "High", "message_text": "Invalid SAP GUI data"},
    "DU1": {"audit_class": "RFC Function Call", "message_severity": "Medium",
            "message_text": "FTP server allowlist is empty"},
    "DU2": {"audit_class": "RFC Function Call", "message_severity": "Medium",
            "message_text": "FTP server allowlist is non-secure due to use of placeholders"},
    "DU3": {"audit_class": "RFC Function Call", "message_severity": "High",
            "message_text": "Server &A is not contained in the allowlist"},
    "DU4": {"audit_class": "RFC Function Call", "message_severity": "High",
            "message_text": "Connection to server &A failed"},
    "DU5": {"audit_class": "RFC Function Call", "message_severity": "High",
            "message_text": "There is no logical file name for path &A"},
    "DU6": {"audit_class": "RFC Function Call", "message_severity": "Low",
            "message_text": "Validation for &A successful"},
    "DU7": {"audit_class": "RFC Function Call", "message_severity": "High", "message_text": "Validation for &A failed"},
    "DU8": {"audit_class": "RFC Function Call", "message_severity": "Low",
            "message_text": "FTP connection request for server &A successful"},
    "DU9": {"audit_class": "Transaction Start", "message_severity": "Low",
            "message_text": "Generic table access call to &A with activity &B (auth. check: &C )"},
    "DUA": {"audit_class": "Other Events", "message_severity": "Medium",
            "message_text": "EHS-SADM: Service &A created on host &B"},
    "DUB": {"audit_class": "Other Events", "message_severity": "Medium",
            "message_text": "EHS-SADM: Service &A started on host &B"},
    "DUC": {"audit_class": "Other Events", "message_severity": "Medium",
            "message_text": "EHS-SADM: Service &A ended on host &B"},
    "DUD": {"audit_class": "Other Events", "message_severity": "Medium",
            "message_text": "EHS-SADM: Service &A deleted on host &B"},
    "DUE": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "EHS-SADM: Configuration of service &A changed on host &B"},
    "DUF": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "EHS-SADM: File &A transferred from host &B"},
    "DUG": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "EHS-SADM: File &A transferred to host &B"},
    "DUH": {"audit_class": "User Master Changes", "message_severity": "Medium",
            "message_text": "OAuth 2.0: Token declared invalid (OAuth client=&A, user=&B, token type=&C)"},
    "DUI": {"audit_class": "RFC Function Call", "message_severity": "Low",
            "message_text": "RFC callback executed (Destination &A, Called &B, Callback &C)"},
    "DUJ": {"audit_class": "RFC Function Call", "message_severity": "High",
            "message_text": "RFC callback rejected (Destination &A, Called &B, Callback &C)"},
    "DUK": {"audit_class": "RFC Function Call", "message_severity": "High",
            "message_text": "RFC callback in simulation mode (Destination &A, Called &B, Callback &C)"},
    "DUL": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "Check for &A in access rule &B was successful"},
    "DUM": {"audit_class": "Other Events", "message_severity": "Medium",
            "message_text": "Check for &A in access rule &B failed"},
    "DUN": {"audit_class": "Other Events", "message_severity": "High",
            "message_text": "Active access rule &A was changed (&B)"},
    "DUO": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "Authorization check for object &A in scenario &B successful"},
    "DUP": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "Authorization check for object &A in scenario &B failed"},
    "DUQ": {"audit_class": "Other Events", "message_severity": "High",
            "message_text": "Active scenario &A for switchable authorization checks changed - &B"},
    "DUR": {"audit_class": "RFC Function Call", "message_severity": "Low",
            "message_text": "JSON RPC call of function module &A succeeded"},
    "DUS": {"audit_class": "RFC Function Call", "message_severity": "Low",
            "message_text": "JSON RPC call of function module &A failed"},
    "DUT": {"audit_class": "RFC Function Call", "message_severity": "High",
            "message_text": "Critical JSON RPC call of function module &A (S_RFC * authorization)"},
    "DUU": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "Authorization check for user &C on object &A in scenario &B successful"},
    "DUV": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "Authorization check for user &C on object &A in scenario &B failed"},
    "DUW": {"audit_class": "Other Events", "message_severity": "Low", "message_text": "Access to Data target in BW &A"},
    "DUX": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "TEMP: Customer-specific event DUX &A &B &C &D"},
    "DUY": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "TEMP: Customer-specific event DUY &A &B &C &D"},
    "DUZ": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "TEMP: Customer-specific event DUZ &A &B &C &D"},
    "EU0": {"audit_class": "Other Events", "message_severity": "Low", "message_text": "Test Message for Class EU"},
    "EU1": {"audit_class": "System Events", "message_severity": "High",
            "message_text": "System change options changed ( &A to &B )"},
    "EU2": {"audit_class": "System Events", "message_severity": "High",
            "message_text": "Client &A settings changed ( &B )"},
    "EU3": {"audit_class": "Other Events", "message_severity": "High",
            "message_text": "&A change documents deleted without archiving (&B)"},
    "EU4": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "Validation successful for logical file name &A (physical: &B)"},
    "EU5": {"audit_class": "System Events", "message_severity": "Low",
            "message_text": "Audit log data of &A was deleted (&B data records)"},
    "EU6": {"audit_class": "System Events", "message_severity": "Low",
            "message_text": "SAL log file &A passed to table &B (records: &C/reason: &D)"},
    "EUA": {"audit_class": "Transaction Start", "message_severity": "Low",
            "message_text": "Invocation of S/4 Cloud SDK ABAP component"},
    "EUB": {"audit_class": "Other Events", "message_severity": "High",
            "message_text": "Digital Signature Verification failed: &A"},
    "EUC": {"audit_class": "Dialog Logon", "message_severity": "High",
            "message_text": "OAuth scope &A not assigned to user"},
    "EUD": {"audit_class": "Dialog Logon", "message_severity": "High",
            "message_text": "HTTP request not received from trustworthy Cloud Connector due to &A"},
    "EUE": {"audit_class": "RFC Function Call", "message_severity": "Low",
            "message_text": "Successful Invocation of Remote Function Module &A"},
    "EUF": {"audit_class": "RFC Function Call", "message_severity": "Low",
            "message_text": "Unsuccessful invocation of Remote Function Module &A"},
    "EUG": {"audit_class": "RFC Function Call", "message_severity": "Low",
            "message_text": "User lacks authorization to invoke Remote Function Module &A"},
    "EUH": {"audit_class": "User Master Changes", "message_severity": "Low",
            "message_text": "User authorizations of user &A for authorization object &B retrieved"},
    "EUI": {"audit_class": "RFC Function Call", "message_severity": "Medium",
            "message_text": "Setup of UCON HTTP White List was changed"},
    "EUJ": {"audit_class": "RFC Function Call", "message_severity": "Medium",
            "message_text": "Status of UCON HTTP White List for context type &A was changed"},
    "EUK": {"audit_class": "RFC Function Call", "message_severity": "High",
            "message_text": "Access to UCON HTTP White List for context type &A was rejected"},
    "EUL": {"audit_class": "RFC Function Call", "message_severity": "Medium",
            "message_text": "HTTP Security Header Register for Header &A was changed"},
    "EUM": {"audit_class": "RFC Function Call", "message_severity": "Medium",
            "message_text": "Trusted Site List &A of HTTP Security Header was changed"},
    "EUN": {"audit_class": "RFC Function Call", "message_severity": "High",
            "message_text": "Content Security Policy for Service &A was violated"},
    "EUO": {"audit_class": "RFC Function Call", "message_severity": "Medium",
            "message_text": "UCON HTTP Whitelist of for context type &A was changed"},
    "EUP": {"audit_class": "Dialog Logon", "message_severity": "High",
            "message_text": "Virtual user client=&A type=&B action=&C &D"},
    "EUQ": {"audit_class": "Report Start", "message_severity": "Medium",
            "message_text": "Analysis program &A &B was started in simulation mode"},
    "EUR": {"audit_class": "Report Start", "message_severity": "High",
            "message_text": "Analysis program &A &B was started in production mode"},
    "EUS": {"audit_class": "Other Events", "message_severity": "Medium","message_text": "Read access to DCT change log (&A)"},
    "EUT": {"audit_class": "Other Events", "message_severity": "Medium",
            "message_text": "DCT change log (&A) was reorganized"},
    "EUU": {"audit_class": "Other Events", "message_severity": "High",
            "message_text": "Suspicious WHERE clause in generic table access on &A (clause &B)"},
    "EUV": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "CDS-View &A (Field &B ) was published"},
    "EUW": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "Blacklisting is enabled (Connection / Table / Field : &A &B &C )"},
    "EUX": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "Blacklisting is disabled (Connection / Table / Field : &A &B &C )"},
    "EUY": {"audit_class": "Other Events", "message_severity": "Low", "message_text": "Data blocking activated for &A"},
    "EUZ": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "Data blocking deactivated for &A"},
    "FU0": {"audit_class": "System Events", "message_severity": "High",
            "message_text": "Exclusive security audit log medium changed (new status &A)"},
    "FU1": {"audit_class": "RFC Function Call", "message_severity": "Low",
            "message_text": "RFC-function &B was called with dynamic destination &C from report &A"},
    "FU2": {"audit_class": "Other Events", "message_severity": "Medium",
            "message_text": "Parsing of an XML data stream was canceled for security reasons (reason=&A)"},
    "FU3": {"audit_class": "Other Events", "message_severity": "Low", "message_text": "Template &A (&B) loaded"},
    "FU4": {"audit_class": "Other Events", "message_severity": "Medium",
            "message_text": "Could not upload template &A"},
    "FU8": {"audit_class": "User Master Changes", "message_severity": "Medium",
            "message_text": "Lock entry deleted for user &A"},
    "FUA": {"audit_class": "Other Events", "message_severity": "High", "message_text": "Audit alert:  &A | &B &C &D"},
    "FUB": {"audit_class": "System Events", "message_severity": "High",
            "message_text": "TEMP: Customer-specific event FUB &A &B &C &D"},
    "FUC": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "Read attempt of output document &A for object &B ( &C )"},
    "FUD": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "Output document &A has been read successfully for object &B ( &C )"},
    "FUE": {"audit_class": "Other Events", "message_severity": "High",
            "message_text": "Output document &A read attempt failed for object &B ( &C )"},
    "GU1": {"audit_class": "Transaction Start", "message_severity": "Low",
            "message_text": "Start authority check for &A ( &B ) successful"},
    "GU2": {"audit_class": "Other Events", "message_severity": "Low",
            "message_text": "Statistic data for log data enrichment collected till &A ( &B entries )"},
    "NU0": {"audit_class": "Other Events", "message_severity": "Low", "message_text": "Audit - Test. Text: &A"},

}